spring:
  application:
    name: tracking-service

  config:
    import: "optional:file:../../tracking.yaml"

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

