server:
  port: 8083

spring:
  application:
    name: workflow-service

tracking:
  url: http://localhost:8082

shipments:
  url: http://localhost:8081

logging:
  level:
    root: INFO
    org.springframework.cloud.openfeign: DEBUG

